version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-api:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      # - run:
      #     name: Install requirements
      #     command: pip install -r api/requirements.txt
      - run:
          name: Install coverage
          command: pip install coverage
      - run:
          name: Run tests and collect coverage
          command: coverage run -m unittest discover api
      - run:
          name: Generate coverage report
          command: coverage xml
      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-api
