name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r api/requirements.txt
    - name: Install coverage
      run: pip install coverage
    - name: Run tests and collect coverage
      run: coverage run -m unittest discover api
    - name: Generate coverage report
      run: coverage xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
